In [11]:
import numpy as np

In [12]:
def createH(fn):
    with open(fn) as f:
        nodes_count = int(f.readline())
        H = np.zeros((nodes_count, nodes_count))

        for row, line in enumerate(f):
            edges = line.split()
            # edge: str x:y
            for edge in edges: 
                edge_from, edges_count = edge.split(':')
                edge_from = int(edge_from)
                edges_count = int(edges_count)

                # divide each node item in matrix by how many edges lead out
                H[row, edge_from] = edges_count/len(edges)

        print("H:\n{}\n".format(H))
        return H

In [13]:
def createS(H):
    S = H.copy()

    for row in range(S.shape[0]):
        row_sum = S[row, :].sum()
         # no edges from this node - add same to get sum one
        if row_sum == 0: 
            S[row, :] = [1/S.shape[0]] * S.shape[0]

    print("S:\n{}\n".format(S))
    return S

In [14]:
def createG(S, alpha):
    G = S.copy()
    e = np.ones(G.shape[0])

    G = alpha*S+(1-alpha)*(1/G.shape[0])*e*e.transpose()

    print("G:\n{}\n".format(G))
    return G

In [48]:
def computePR(M, iterations):

    #create page rank matrix
    
    pagerank = np.zeros(size)
    pagerank = np.ones(M.shape[0])

    # init one item to one 
    
    pagerank[0] = 1
    pagerank = pagerank/M.shape[0]
    

    for i in range(iterations):
        pagerank = pagerank.transpose() @ M
        print("%s: %s - sum: %s" % (i+1, pagerank, pagerank.sum()))

    return pagerank

In [66]:
def print_fo_file(file, iterations = 15, alfa = 0.9):
    
    matrix_H = createH(file)  

    matrix_S = createS(matrix_H)

    # (alpha) - if 1, equals to S. 1 not work
    matrix_G = createG(matrix_S, alfa)

    print('with matrix H')
    h = computePR(matrix_H, iterations)
    print()
    print('with matrix S')
    s = computePR(matrix_S, iterations)
    print()
    print('with Google matrix (G)')
    g = computePR(matrix_G, iterations)
    print()
    print_pr('PageRank H ', h)
    print_pr('PageRank S ', s)
    print_pr('PageRank G ', g)    
    
def print_pr(title, vector):
    print(title)
    for i, j in enumerate(vector):
        print('Node: %s Rank: %s' % (i, j))

In [67]:
# values oscillate without convergence
print_fo_file('test1.txt', iterations=5)

H:
[[0. 1.]
 [1. 0.]]

S:
[[0. 1.]
 [1. 0.]]

G:
[[0.05 0.95]
 [0.95 0.05]]

with matrix H
1: [0.5 0.5] - sum: 1.0
2: [0.5 0.5] - sum: 1.0
3: [0.5 0.5] - sum: 1.0
4: [0.5 0.5] - sum: 1.0
5: [0.5 0.5] - sum: 1.0

with matrix S
1: [0.5 0.5] - sum: 1.0
2: [0.5 0.5] - sum: 1.0
3: [0.5 0.5] - sum: 1.0
4: [0.5 0.5] - sum: 1.0
5: [0.5 0.5] - sum: 1.0

with Google matrix (G)
1: [0.5 0.5] - sum: 1.0
2: [0.5 0.5] - sum: 1.0
3: [0.5 0.5] - sum: 1.0
4: [0.5 0.5] - sum: 1.0
5: [0.5 0.5] - sum: 1.0

PageRank H 
Node: 0 Rank: 0.5
Node: 1 Rank: 0.5
PageRank S 
Node: 0 Rank: 0.5
Node: 1 Rank: 0.5
PageRank G 
Node: 0 Rank: 0.5
Node: 1 Rank: 0.5


In [68]:
# oscilation between two nodes
print_fo_file('test2.txt', iterations=6) 

H:
[[0.         0.33333333 0.33333333 0.33333333]
 [0.         0.         1.         0.        ]
 [0.         0.         0.         1.        ]
 [0.         0.         1.         0.        ]]

S:
[[0.         0.33333333 0.33333333 0.33333333]
 [0.         0.         1.         0.        ]
 [0.         0.         0.         1.        ]
 [0.         0.         1.         0.        ]]

G:
[[0.025 0.325 0.325 0.325]
 [0.025 0.025 0.925 0.025]
 [0.025 0.025 0.025 0.925]
 [0.025 0.025 0.925 0.025]]

with matrix H
1: [0.         0.08333333 0.58333333 0.33333333] - sum: 1.0
2: [0.         0.         0.41666667 0.58333333] - sum: 0.9999999999999999
3: [0.         0.         0.58333333 0.41666667] - sum: 0.9999999999999999
4: [0.         0.         0.41666667 0.58333333] - sum: 0.9999999999999999
5: [0.         0.         0.58333333 0.41666667] - sum: 0.9999999999999999
6: [0.         0.         0.41666667 0.58333333] - sum: 0.9999999999999999

with matrix S
1: [0.         0.08333333 0.58333333 

In [69]:
#with high number of iteration sums go 0 
print_fo_file('test3.txt', alfa=0.1, iterations=40)

H:
[[0.         0.5        0.5        0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.5        0.5       ]
 [0.33333333 0.33333333 0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.5        0.         0.5       ]
 [0.         0.         0.         1.         0.         0.        ]]

S:
[[0.         0.5        0.5        0.         0.         0.        ]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.         0.         0.         0.         0.5        0.5       ]
 [0.33333333 0.33333333 0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.5        0.         0.5       ]
 [0.         0.         0.         1.         0.         0.        ]]

G:
[[0.15       0.2        0.2        0.15       0.15       0.15      ]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.15       0.15    

In [72]:
print_fo_file('test4.txt', iterations=20, alfa=0.90)

H:
[[0.  0.5 0.5]
 [1.  0.  0. ]
 [0.  1.  0. ]]

S:
[[0.  0.5 0.5]
 [1.  0.  0. ]
 [0.  1.  0. ]]

G:
[[0.03333333 0.48333333 0.48333333]
 [0.93333333 0.03333333 0.03333333]
 [0.03333333 0.93333333 0.03333333]]

with matrix H
1: [0.33333333 0.5        0.16666667] - sum: 0.9999999999999999
2: [0.5        0.33333333 0.16666667] - sum: 0.9999999999999999
3: [0.33333333 0.41666667 0.25      ] - sum: 1.0
4: [0.41666667 0.41666667 0.16666667] - sum: 0.9999999999999999
5: [0.41666667 0.375      0.20833333] - sum: 1.0
6: [0.375      0.41666667 0.20833333] - sum: 1.0
7: [0.41666667 0.39583333 0.1875    ] - sum: 1.0
8: [0.39583333 0.39583333 0.20833333] - sum: 1.0
9: [0.39583333 0.40625    0.19791667] - sum: 0.9999999999999999
10: [0.40625    0.39583333 0.19791667] - sum: 0.9999999999999999
11: [0.39583333 0.40104167 0.203125  ] - sum: 1.0
12: [0.40104167 0.40104167 0.19791667] - sum: 0.9999999999999999
13: [0.40104167 0.3984375  0.20052083] - sum: 1.0
14: [0.3984375  0.40104167 0.20052083] - s